ALTER TABLE "GlobalSettings"
ADD COLUMN "tokenInputUsdPer1M" DECIMAL(12, 4) NOT NULL DEFAULT 0.40,
ADD COLUMN "tokenOutputUsdPer1M" DECIMAL(12, 4) NOT NULL DEFAULT 1.60,
ADD COLUMN "tokenCachedInputUsdPer1M" DECIMAL(12, 4) NOT NULL DEFAULT 0.10,
ADD COLUMN "tokenMarkupPercent" DECIMAL(5, 2) NOT NULL DEFAULT 30.00;

ALTER TABLE "TokenUsageLog"
ADD COLUMN "costUsdMicros" INTEGER,
ADD COLUMN "billedAt" TIMESTAMP(3);
