import { requirePartner } from '@/lib/partners/access';
import { getPartnerEntries, getPartnerProjects } from '@/lib/partners/workspace-data';
import { addWorkspaceEntry } from '../actions';
import { EntryList, WorkspaceHeader } from '@/components/partner/workspace-ui';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';

const transversal = ['Estrategia y objetivos','Organización y gobierno','Procesos y operaciones','Talento y capacidades','Finanzas y control','Comercial y clientes','Datos e indicadores','Tecnología e integraciones','Automatización','Inteligencia artificial','Ciberseguridad','KPIs y mejora continua'];
const sectorial = ['Licitaciones B2B','Contratos y cobranza','Cadena de suministro','Operaciones de campo','Flota y activos','Capital humano','Permisología','Seguridad, higiene, ambiente y calidad'];

export default async function DiscoveryPage({params}:{params:Promise<{locale:string}>}){const{locale}=await params;const{partner}=await requirePartner(locale);const[projects,entries]=await Promise.all([getPartnerProjects(partner.id),getPartnerEntries(partner.id,['DISCOVERY','FACT','ASSUMPTION','OPEN_QUESTION','RISK','REQUIREMENT'])]);return <div className="space-y-6"><WorkspaceHeader eyebrow="Metodología EFICI" title="Levantamientos" description="Diagnóstico guiado transversal y sectorial. Clasifica cada hallazgo para que el expediente distinga con claridad lo confirmado, lo supuesto, lo pendiente y lo riesgoso."/>
  <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Diagnóstico transversal</CardTitle></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-2">{transversal.map((x,i)=><div key={x} className="rounded-lg border p-3 text-sm"><span className="mr-2 font-semibold text-[#00aeb3]">{i+1}.</span>{x}</div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Módulos sectoriales</CardTitle></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-2">{sectorial.map(x=><div key={x} className="rounded-lg border p-3 text-sm">{x}</div>)}</div></CardContent></Card></div>
  <div className="grid gap-6 xl:grid-cols-[420px_1fr]"><Card><CardHeader><CardTitle>Registrar hallazgo</CardTitle></CardHeader><CardContent>{projects.length===0?<p className="text-sm text-slate-500">Primero crea una oportunidad.</p>:<form action={addWorkspaceEntry} className="space-y-4"><input type="hidden" name="locale" value={locale}/><div className="space-y-2"><Label>Proyecto</Label><select name="opportunityId" className="w-full rounded-md border px-3 py-2 text-sm">{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.targetCompany}</option>)}</select></div><div className="space-y-2"><Label>Módulo evaluado</Label><select name="title" className="w-full rounded-md border px-3 py-2 text-sm">{[...transversal,...sectorial].map(x=><option key={x}>{x}</option>)}</select></div><div className="space-y-2"><Label>Clasificación</Label><select name="category" defaultValue="FACT" className="w-full rounded-md border px-3 py-2 text-sm"><option value="FACT">Hecho confirmado</option><option value="ASSUMPTION">Supuesto de trabajo</option><option value="OPEN_QUESTION">Pregunta abierta</option><option value="RISK">Riesgo</option><option value="REQUIREMENT">Requerimiento</option><option value="DISCOVERY">Nota de levantamiento</option></select></div><div className="space-y-2"><Label>Confianza</Label><select name="confidence" defaultValue="CONFIRMED" className="w-full rounded-md border px-3 py-2 text-sm"><option value="CONFIRMED">Confirmado</option><option value="RESEARCHED">Investigado</option><option value="INFERRED">Inferido</option><option value="WORKING_ASSUMPTION">Supuesto</option></select></div><div className="space-y-2"><Label>Fuente</Label><input name="sourceLabel" required placeholder="Entrevista, documento o área responsable" className="w-full rounded-md border px-3 py-2 text-sm"/></div><div className="space-y-2"><Label>Hallazgo o pregunta</Label><textarea name="content" rows={7} required className="w-full rounded-xl border px-4 py-3 text-sm"/></div><Button className="w-full">Guardar en el expediente</Button></form>}</CardContent></Card><EntryList locale={locale} entries={entries}/></div>
  </div>}
