import Link from 'next/link';
import { notFound } from 'next/navigation';
import { prisma } from '@trends172tech/db';
import { requirePartner } from '@/lib/partners/access';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

type ProjectRow={id:string;name:string;targetCompany:string;clientContact:string|null;stage:string;objective:string|null;knownContext:string|null;requestedNeed:string|null;status:string;agentName:string|null;agentStatus:string|null;executiveSummary:string|null;currentStageSummary:string|null;confirmedFacts:unknown;assumptions:unknown;openQuestions:unknown;risks:unknown;nextActions:unknown;readinessScore:number};
type EntryRow={id:string;category:string;content:string;sourceType:string;sourceLabel:string|null;confidence:string;createdAt:Date};
const asList=(v:unknown)=>Array.isArray(v)?v.map(String):[];

export default async function ProjectWorkspace({params}:{params:Promise<{locale:string;id:string}>}){const {locale,id}=await params;const {partner}=await requirePartner(locale);const rows=await prisma.$queryRaw<ProjectRow[]>`SELECT o."id",o."name",o."targetCompany",o."clientContact",o."stage",o."objective",o."knownContext",o."requestedNeed",o."status",a."name" AS "agentName",a."status" AS "agentStatus",m."executiveSummary",m."currentStageSummary",m."confirmedFacts",m."assumptions",m."openQuestions",m."risks",m."nextActions",m."readinessScore" FROM "PartnerOpportunity" o LEFT JOIN "ProjectAgent" a ON a."opportunityId"=o."id" LEFT JOIN "ProjectMemory" m ON m."opportunityId"=o."id" WHERE o."id"=${id} AND o."partnerId"=${partner.id} LIMIT 1`;const project=rows[0];if(!project)notFound();const entries=await prisma.$queryRaw<EntryRow[]>`SELECT "id","category","content","sourceType","sourceLabel","confidence","createdAt" FROM "ProjectMemoryEntry" WHERE "opportunityId"=${id} AND "isCurrent"=true AND "category" NOT IN ('CHAT_USER','CHAT_AGENT') ORDER BY "createdAt" DESC LIMIT 50`;
const sections=[['Hechos confirmados',asList(project.confirmedFacts)],['Supuestos de trabajo',asList(project.assumptions)],['Preguntas abiertas',asList(project.openQuestions)],['Riesgos',asList(project.risks)],['Próximas acciones',asList(project.nextActions)]] as const;
return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-red-600">Expediente vivo · {project.stage}</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">{project.name}</h2><p className="mt-2 text-sm text-slate-500">{project.targetCompany}{project.clientContact?` · ${project.clientContact}`:''}</p></div><div className="flex gap-2"><Button variant="outline">Agregar avance</Button><Button asChild><Link href={`/${locale}/partner/projects/${id}/agent`}>Hablar con agente del proyecto</Link></Button></div></div>
<div className="grid gap-4 md:grid-cols-4"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Preparación</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{project.readinessScore??0}%</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-red-600" style={{width:`${project.readinessScore??0}%`}}/></div></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Agente</CardTitle></CardHeader><CardContent><div className="font-semibold">{project.agentName??'Sin agente'}</div><p className="mt-1 text-xs text-slate-500">{project.agentStatus??'PENDING'} · memoria aislada</p></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Estado</CardTitle></CardHeader><CardContent><div className="font-semibold">{project.status}</div><p className="mt-1 text-xs text-slate-500">Oportunidad</p></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Memoria</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{entries.length}</div><p className="mt-1 text-xs text-slate-500">entradas de conocimiento</p></CardContent></Card></div>
<div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-6"><Card><CardHeader><CardTitle>Resumen ejecutivo</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="font-medium">Objetivo</p><p className="mt-1 text-slate-600">{project.objective||'Pendiente de definir.'}</p></div><div><p className="font-medium">Necesidad planteada</p><p className="mt-1 text-slate-600">{project.requestedNeed||'Pendiente de levantar.'}</p></div><div><p className="font-medium">Resumen vivo</p><p className="mt-1 text-slate-600">{project.executiveSummary||project.knownContext||'El agente todavía no ha consolidado un resumen.'}</p></div></CardContent></Card><div className="grid gap-4 md:grid-cols-2">{sections.map(([title,items])=><Card key={title}><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent>{items.length?<ul className="space-y-2 text-sm">{items.map((item,i)=><li key={i} className="rounded-lg border p-3">{item}</li>)}</ul>:<p className="text-sm text-slate-500">Sin elementos todavía.</p>}</CardContent></Card>)}</div></div><div className="space-y-6"><Card><CardHeader><CardTitle>Project Agent</CardTitle></CardHeader><CardContent><div className="rounded-xl border bg-slate-50 p-4"><p className="text-sm font-semibold">¿Qué hacemos ahora?</p><p className="mt-2 text-sm text-slate-600">El agente utiliza únicamente el expediente de esta oportunidad y mantiene una conversación persistente separada de la memoria curada.</p><Button className="mt-4 w-full" asChild><Link href={`/${locale}/partner/projects/${id}/agent`}>Abrir conversación</Link></Button></div></CardContent></Card><Card><CardHeader><CardTitle>Memoria reciente</CardTitle></CardHeader><CardContent>{entries.length?<div className="space-y-3">{entries.map(e=><div key={e.id} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold uppercase text-red-600">{e.category}</span><span className="text-[11px] text-slate-400">{e.confidence}</span></div><p className="mt-2 text-sm">{e.content}</p><p className="mt-2 text-[11px] text-slate-400">{e.sourceLabel||e.sourceType}</p></div>)}</div>:<p className="text-sm text-slate-500">Todavía no hay memoria registrada.</p>}</CardContent></Card></div></div></div>}
