import Link from 'next/link';
import { requirePartner } from '@/lib/partners/access';
import { getPartnerProjects } from '@/lib/partners/workspace-data';
import { WorkspaceHeader } from '@/components/partner/workspace-ui';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

export default async function DirectorPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; const { partner } = await requirePartner(locale); const projects = await getPartnerProjects(partner.id);
  return <div className="space-y-7"><WorkspaceHeader eyebrow="Business Discovery Agent" title="Director B2B" description="Selecciona una oportunidad para conversar con su agente especializado. Cada conversación usa únicamente la memoria de ese proyecto y mantiene separados hechos, supuestos, preguntas, riesgos y próximas acciones."/>
    <div className="grid gap-5 md:grid-cols-2">{projects.length ? projects.map(p=><Card key={p.id} className="group border-black/[.06] transition hover:-translate-y-1 hover:border-[#a7e4e5] hover:shadow-[0_28px_70px_-50px_rgba(0,120,125,.45)]"><CardHeader className="border-0 pb-2"><div className="mb-5 flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#effbfa] text-sm font-semibold text-[#00aeb3]">B2B</span><span className="rounded-full border border-[#bcebed] bg-[#f5fbfa] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-[#009fa4]">Activo</span></div><CardTitle className="text-xl">{p.name}</CardTitle></CardHeader><CardContent><p className="mb-5 text-sm text-[#68717b]">{p.targetCompany}</p><Button asChild className="w-full group-hover:bg-[#009fa4]"><Link href={`/${locale}/partner/projects/${p.id}/agent`}>Abrir Director B2B del proyecto →</Link></Button></CardContent></Card>) : <Card className="border-[#c5e8e8] bg-[linear-gradient(145deg,#ffffff,#f0faf9)] md:col-span-2"><CardContent className="px-7 py-12 sm:px-12"><div className="grid items-center gap-8 lg:grid-cols-[1fr_auto]"><div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-sm font-semibold text-[#00aeb3] shadow-[0_12px_30px_-20px_rgba(0,120,125,.5)]">B2B</span><h3 className="mt-5 font-[var(--font-display)] text-2xl font-semibold tracking-[-.04em]">Activa tu primer Director B2B</h3><p className="mt-2 max-w-xl text-sm leading-7 text-[#68717b]">Crea una oportunidad para generar su expediente empresarial, memoria independiente y espacio de acompañamiento especializado.</p></div><Button asChild className="hover:bg-[#009fa4]"><Link href={`/${locale}/partner/projects`}>Crear primera oportunidad →</Link></Button></div></CardContent></Card>}</div>
  </div>;
}
