// Script para generar SQL de inserción de skills sin conexión a BD
import { writeFileSync } from 'fs';

const SKILLS = [
  { key: 'cocina', name: 'Cocina', nameEn: 'Kitchen', industry: 'hogar', industryEn: 'Home & Construction', icon: '🍳', description: 'Asesoría experta en diseño y configuración de cocinas: materiales, colores, presupuesto.', descriptionEn: 'Expert advisory for kitchen design and configuration: materials, colors, budget.', priceMonthly: 15, isFeatured: true, sortOrder: 1, promptJson: { system: 'Eres un asesor experto en diseño de cocinas.', instructions: ['Pregunta dimensiones', 'Ofrece opciones de precio', 'Explica materiales', 'Prioriza según presupuesto'] }, mapJson: { secciones: ['muebles_superiores','muebles_inferiores','perfil_gola','meson_superficie','fregadero_griferia','accesorios_internos','iluminacion','piso','revestimiento_paredes','isla','electrodomesticos','electrico','tornilleria','decoracion'] }, questionsJson: [{ id: 'dimensiones', question: '¿Dimensiones del espacio?', type: 'text' },{ id: 'presupuesto', question: '¿Presupuesto estimado?', type: 'text' },{ id: 'estilo', question: '¿Estilo preferido?', type: 'select', options: ['moderno','clasico','rustico','minimalista'] }] },
  { key: 'bano', name: 'Baño', nameEn: 'Bathroom', industry: 'hogar', industryEn: 'Home & Construction', icon: '🚿', description: 'Diseño y asesoría en remodelación de baños: griferías, revestimientos, sanitarios.', descriptionEn: 'Bathroom remodeling advisory: fixtures, tiles, sanitary ware.', priceMonthly: 15, isFeatured: false, sortOrder: 2, promptJson: { system: 'Eres un asesor experto en diseño de baños.', instructions: ['Pregunta si es remodelación total o parcial','Consulta presupuesto','Explica materiales','Sugiere tendencias'] }, mapJson: { secciones: ['sanitarios','griferia','revestimiento_piso','revestimiento_paredes','mueble_vanidad','espejo','accesorios','iluminacion','ventilacion'] }, questionsJson: [{ id: 'tipo', question: '¿Tipo de baño?', type: 'select', options: ['principal','secundario','servicio'] },{ id: 'presupuesto', question: '¿Presupuesto?', type: 'text' }] },
  { key: 'closet', name: 'Clóset', nameEn: 'Closet', industry: 'hogar', industryEn: 'Home & Construction', icon: '👔', description: 'Asesoría en diseño de clósets y vestidores a medida.', descriptionEn: 'Custom closet and dressing room design.', priceMonthly: 15, isFeatured: false, sortOrder: 3, promptJson: { system: 'Eres un asesor experto en clósets a medida.', instructions: ['Pregunta dimensiones y apertura','Consulta qué se guarda','Propón distribución','Sugiere materiales'] }, mapJson: { secciones: ['colgadores','cajones','estantes','zapatera','accesorios_internos','puertas','iluminacion','espejo'] }, questionsJson: [{ id: 'dimensiones', question: '¿Dimensiones?', type: 'text' },{ id: 'tipo_apertura', question: '¿Tipo de apertura?', type: 'select', options: ['corredizas','abatibles','sin_puertas','walk_in'] }] },
  { key: 'sala_tv', name: 'Sala / Mueble TV', nameEn: 'Living Room / TV Cabinet', industry: 'hogar', industryEn: 'Home & Construction', icon: '🛋️', description: 'Diseño de salas de estar y muebles para TV.', descriptionEn: 'Living room and TV cabinet design.', priceMonthly: 15, isFeatured: false, sortOrder: 4, promptJson: { system: 'Eres asesor de salas y muebles TV.', instructions: ['Pregunta tamaño TV','Consulta almacenamiento','Sugiere materiales','Considera flujo de personas'] }, mapJson: { secciones: ['mueble_tv','sofa','mesa_centro','estanteria','iluminacion','decoracion','alfombra'] }, questionsJson: [{ id: 'dimension_tv', question: '¿Tamaño TV (pulgadas)?', type: 'text' },{ id: 'estilo', question: '¿Estilo?', type: 'select', options: ['moderno','clasico','minimalista','industrial'] }] },
  { key: 'dormitorio', name: 'Dormitorio', nameEn: 'Bedroom', industry: 'hogar', industryEn: 'Home & Construction', icon: '🛏️', description: 'Diseño completo de dormitorios: camas, mesas de noche, cómodas.', descriptionEn: 'Complete bedroom design.', priceMonthly: 15, isFeatured: false, sortOrder: 5, promptJson: { system: 'Eres asesor experto en dormitorios.', instructions: ['Pregunta tipo de dormitorio','Consulta dimensiones','Sugiere distribución','Recomienda paleta de colores'] }, mapJson: { secciones: ['cama','cabecero','mesitas_noche','comoda','espejo','iluminacion','cortinas','alfombra','closet'] }, questionsJson: [{ id: 'tipo', question: '¿Tipo?', type: 'select', options: ['principal','infantil','huespedes'] },{ id: 'cama', question: '¿Tamaño de cama?', type: 'select', options: ['sencilla','doble','queen','king'] }] },
  { key: 'odontologia', name: 'Odontología', nameEn: 'Dentistry', industry: 'salud', industryEn: 'Health', icon: '🦷', description: 'Recepcionista virtual para consultorios dentales: citas, tratamientos, FAQ.', descriptionEn: 'Virtual receptionist for dental offices.', priceMonthly: 15, isFeatured: true, sortOrder: 1, promptJson: { system: 'Eres asistente virtual de un consultorio odontológico.', instructions: ['No des diagnósticos médicos','Ofrece citas ante síntomas','Informa tratamientos','Recuerda llevar seguro'] }, mapJson: { servicios: ['limpieza','blanqueamiento','ortodoncia','implantes','extracciones','endodoncia','protesis','cirugia_oral'] }, questionsJson: [{ id: 'motivo', question: '¿Motivo de consulta?', type: 'text' },{ id: 'primera_vez', question: '¿Primera visita?', type: 'boolean' }] },
  { key: 'medicina_general', name: 'Medicina General', nameEn: 'General Medicine', industry: 'salud', industryEn: 'Health', icon: '🩺', description: 'Asistente para consultorios médicos: citas e información.', descriptionEn: 'Assistant for medical offices.', priceMonthly: 15, isFeatured: false, sortOrder: 2, promptJson: { system: 'Eres asistente virtual de medicina general.', instructions: ['No diagnostiques','Recomienda consulta presencial','Informa horarios','Explica preparativos para exámenes'] }, mapJson: { servicios: ['consulta_general','examenes_laboratorio','vacunacion','medicina_preventiva','certificados_medicos'] }, questionsJson: [{ id: 'motivo', question: '¿Motivo de consulta?', type: 'text' },{ id: 'primera_vez', question: '¿Primera vez?', type: 'boolean' }] },
  { key: 'nutricion', name: 'Nutrición', nameEn: 'Nutrition', industry: 'salud', industryEn: 'Health', icon: '🥗', description: 'Orientación nutricional y agenda de consultas.', descriptionEn: 'Nutritional guidance and appointment scheduling.', priceMonthly: 15, isFeatured: false, sortOrder: 3, promptJson: { system: 'Eres asistente de nutrición.', instructions: ['No diseñes planes sin consulta','Informa programas disponibles','Agenda citas','Motiva hábitos saludables'] }, mapJson: { servicios: ['consulta_inicial','plan_alimentacion','seguimiento','nutricion_deportiva','perdida_peso'] }, questionsJson: [{ id: 'objetivo', question: '¿Objetivo nutricional?', type: 'select', options: ['perder_peso','ganar_masa','mejorar_habitos','condicion_clinica','rendimiento_deportivo'] }] },
  { key: 'compra_venta_inmueble', name: 'Compra y Venta', nameEn: 'Buy & Sell', industry: 'inmobiliaria', industryEn: 'Real Estate', icon: '🏠', description: 'Asesor inmobiliario para compra y venta de propiedades.', descriptionEn: 'Real estate advisor for buying and selling.', priceMonthly: 15, isFeatured: true, sortOrder: 1, promptJson: { system: 'Eres asesor inmobiliario experto en compra y venta.', instructions: ['Pregunta presupuesto y zona','Explica proceso de compra','Informa financiamiento','Agenda visitas'] }, mapJson: { tipos_inmueble: ['apartamento','casa','local_comercial','oficina','terreno','galpon'], etapas: ['busqueda','visita','oferta','documentacion','cierre'] }, questionsJson: [{ id: 'operacion', question: '¿Comprar o vender?', type: 'select', options: ['comprar','vender','ambos'] },{ id: 'zona', question: '¿Zona?', type: 'text' },{ id: 'presupuesto', question: '¿Presupuesto?', type: 'text' }] },
  { key: 'alquiler_temporal', name: 'Alquiler Temporal', nameEn: 'Short-Term Rental', industry: 'inmobiliaria', industryEn: 'Real Estate', icon: '🗓️', description: 'Gestión de alquileres temporales: disponibilidad, tarifas y check-in.', descriptionEn: 'Short-term rental management.', priceMonthly: 15, isFeatured: false, sortOrder: 2, promptJson: { system: 'Eres asistente de alquileres temporales.', instructions: ['Consulta fechas y huéspedes','Informa normas','Explica proceso de reserva','Asiste durante estadía'] }, mapJson: { etapas: ['consulta_disponibilidad','cotizacion','reserva','check_in','estadia','check_out','valoracion'] }, questionsJson: [{ id: 'fechas', question: '¿Fechas de entrada y salida?', type: 'text' },{ id: 'huespedes', question: '¿Número de huéspedes?', type: 'text' }] },
  { key: 'ferreteria', name: 'Ferretería', nameEn: 'Hardware Store', industry: 'retail', industryEn: 'Retail', icon: '🔨', description: 'Asistente para ferreterías: productos, stock y precios.', descriptionEn: 'Hardware store assistant.', priceMonthly: 15, isFeatured: false, sortOrder: 1, promptJson: { system: 'Eres asistente virtual de una ferretería.', instructions: ['Pregunta para qué proyecto','Explica diferencias técnicas','Informa disponibilidad','Sugiere productos complementarios'] }, mapJson: { categorias: ['herramientas_manuales','herramientas_electricas','materiales_construccion','plomeria','electricidad','pintura','fijaciones'] }, questionsJson: [{ id: 'proyecto', question: '¿Para qué proyecto?', type: 'text' },{ id: 'producto', question: '¿Qué producto buscas?', type: 'text' }] },
  { key: 'ropa_calzado', name: 'Ropa y Calzado', nameEn: 'Clothing & Footwear', industry: 'retail', industryEn: 'Retail', icon: '👗', description: 'Asesor de moda: tallas, estilos y tendencias.', descriptionEn: 'Fashion advisor for clothing and footwear.', priceMonthly: 15, isFeatured: false, sortOrder: 2, promptJson: { system: 'Eres asesor de moda de una tienda de ropa y calzado.', instructions: ['Pregunta talla y ocasión','Sugiere combinaciones','Informa disponibilidad','Comparte tendencias'] }, mapJson: { categorias: ['camisas','pantalones','vestidos','ropa_deportiva','calzado_casual','calzado_formal','calzado_deportivo'] }, questionsJson: [{ id: 'genero', question: '¿Para quién?', type: 'select', options: ['hombre','mujer','nino','nina'] },{ id: 'talla', question: '¿Talla?', type: 'text' },{ id: 'ocasion', question: '¿Ocasión?', type: 'select', options: ['casual','formal','deportivo','trabajo'] }] },
  { key: 'farmacia', name: 'Farmacia', nameEn: 'Pharmacy', industry: 'retail', industryEn: 'Retail', icon: '💊', description: 'Asistente farmacéutico: medicamentos e información.', descriptionEn: 'Pharmacy assistant.', priceMonthly: 15, isFeatured: false, sortOrder: 3, promptJson: { system: 'Eres asistente de una farmacia.', instructions: ['No recomiendas sin receta','Informa disponibilidad','Orienta sobre suplementos','Recomienda consultar médico'] }, mapJson: { categorias: ['medicamentos_otc','vitaminas_suplementos','cuidado_personal','bebe','dermatologia'] }, questionsJson: [{ id: 'producto', question: '¿Qué buscas?', type: 'text' },{ id: 'receta', question: '¿Tienes receta?', type: 'boolean' }] },
  { key: 'electrodomesticos_retail', name: 'Electrodomésticos', nameEn: 'Home Appliances', industry: 'retail', industryEn: 'Retail', icon: '📺', description: 'Asesor de electrodomésticos: características, comparativas y garantías.', descriptionEn: 'Appliance and technology advisor.', priceMonthly: 15, isFeatured: false, sortOrder: 4, promptJson: { system: 'Eres asesor de electrodomésticos y tecnología.', instructions: ['Pregunta uso y espacio','Compara modelos','Informa garantía','Sugiere accesorios'] }, mapJson: { categorias: ['televisores','refrigeradores','lavadoras','aires_acondicionados','microondas','computadoras','celulares'] }, questionsJson: [{ id: 'producto', question: '¿Qué buscas?', type: 'text' },{ id: 'presupuesto', question: '¿Presupuesto?', type: 'text' }] },
  { key: 'ventas_foraneas', name: 'Ventas Foráneas', nameEn: 'Field Sales', industry: 'empresas', industryEn: 'Enterprise Teams', icon: '🚗', description: 'Coordinador de ventas en campo: rutas, pedidos y reportes.', descriptionEn: 'Field sales team coordinator.', priceMonthly: 25, isFeatured: true, sortOrder: 1, promptJson: { system: 'Eres coordinador virtual de ventas foráneas.', instructions: ['Registra pedidos con cliente y productos','Consulta disponibilidad','Registra resultado de visita','Genera resúmenes diarios'] }, mapJson: { flujo: ['apertura_ruta','visita_cliente','toma_pedido','registro_resultado','cierre_ruta'] }, questionsJson: [{ id: 'vendedor', question: '¿Nombre y zona?', type: 'text' },{ id: 'tipo_registro', question: '¿Qué registras?', type: 'select', options: ['pedido','visita_sin_pedido','cobranza','incidencia'] }] },
  { key: 'pedidos_internos', name: 'Gestión de Pedidos', nameEn: 'Order Management', industry: 'empresas', industryEn: 'Enterprise Teams', icon: '📦', description: 'Gestión de pedidos internos y coordinación entre áreas.', descriptionEn: 'Internal order management.', priceMonthly: 25, isFeatured: false, sortOrder: 2, promptJson: { system: 'Eres asistente de gestión de pedidos internos.', instructions: ['Registra solicitudes con área y urgencia','Consulta estados','Notifica pedidos urgentes','Resume pendientes'] }, mapJson: { estados: ['recibido','en_proceso','listo_despacho','despachado','entregado','cancelado'], areas: ['produccion','almacen','despacho','compras'] }, questionsJson: [{ id: 'solicitante', question: '¿Quién solicita y de qué área?', type: 'text' },{ id: 'urgencia', question: '¿Es urgente?', type: 'boolean' }] },
  { key: 'soporte_cliente', name: 'Soporte al Cliente', nameEn: 'Customer Support', industry: 'empresas', industryEn: 'Enterprise Teams', icon: '🎧', description: 'Agente de soporte: tickets, seguimiento y resolución.', descriptionEn: 'Customer support agent.', priceMonthly: 20, isFeatured: false, sortOrder: 3, promptJson: { system: 'Eres agente de soporte al cliente.', instructions: ['Escucha el problema completo','Registra ticket','Escala cuando sea necesario','Haz seguimiento proactivo'] }, mapJson: { tipos_ticket: ['consulta','queja','solicitud','soporte_tecnico','devolucion','facturacion'] }, questionsJson: [{ id: 'tipo', question: '¿Tipo de solicitud?', type: 'select', options: ['consulta','queja','soporte_tecnico','devolucion'] },{ id: 'descripcion', question: '¿Describe el problema:', type: 'text' }] },
  { key: 'rrhh', name: 'Recursos Humanos', nameEn: 'Human Resources', industry: 'empresas', industryEn: 'Enterprise Teams', icon: '👥', description: 'Asistente de RRHH: vacaciones, permisos y documentación.', descriptionEn: 'HR assistant.', priceMonthly: 20, isFeatured: false, sortOrder: 4, promptJson: { system: 'Eres asistente de Recursos Humanos.', instructions: ['Responde sobre políticas','Registra solicitudes de vacaciones','Informa onboarding','Orienta sobre documentación'] }, mapJson: { tramites: ['vacaciones','permiso_medico','permiso_personal','constancia_trabajo','onboarding'] }, questionsJson: [{ id: 'empleado', question: '¿Nombre y departamento?', type: 'text' },{ id: 'tramite', question: '¿Qué trámite necesitas?', type: 'select', options: ['vacaciones','permiso','constancia','consulta_politica'] }] },
];

function esc(str: string): string {
  return str.replace(/'/g, "''");
}

const lines: string[] = ['-- Seed de 18 skills para Agent Creator'];
lines.push('-- Ejecutar en Neon SQL Editor\n');

for (const s of SKILLS) {
  const id = `skill_${s.key}`;
  const now = 'NOW()';
  lines.push(`INSERT INTO "Skill" ("id","key","name","nameEn","industry","industryEn","icon","description","descriptionEn","promptJson","mapJson","questionsJson","priceMonthly","isActive","isFeatured","sortOrder","createdAt","updatedAt")`);
  lines.push(`VALUES (`);
  lines.push(`  '${id}',`);
  lines.push(`  '${esc(s.key)}',`);
  lines.push(`  '${esc(s.name)}',`);
  lines.push(`  '${esc(s.nameEn)}',`);
  lines.push(`  '${esc(s.industry)}',`);
  lines.push(`  '${esc(s.industryEn)}',`);
  lines.push(`  '${esc(s.icon)}',`);
  lines.push(`  '${esc(s.description)}',`);
  lines.push(`  '${esc(s.descriptionEn)}',`);
  lines.push(`  '${esc(JSON.stringify(s.promptJson))}'::jsonb,`);
  lines.push(`  '${esc(JSON.stringify(s.mapJson))}'::jsonb,`);
  lines.push(`  '${esc(JSON.stringify(s.questionsJson))}'::jsonb,`);
  lines.push(`  ${s.priceMonthly},`);
  lines.push(`  true,`);
  lines.push(`  ${s.isFeatured},`);
  lines.push(`  ${s.sortOrder},`);
  lines.push(`  ${now},`);
  lines.push(`  ${now}`);
  lines.push(`) ON CONFLICT ("key") DO NOTHING;\n`);
}

const sql = lines.join('\n');
writeFileSync('scripts/skills-seed.sql', sql, 'utf8');
console.log(`Generated SQL with ${SKILLS.length} skills → scripts/skills-seed.sql`);
