import Link from 'next/link';
import { notFound } from 'next/navigation';
import { prisma } from '@trends172tech/db';
import { requirePartner } from '@/lib/partners/access';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type ProjectRow={id:string;name:string;targetCompany:string;clientContact:string|null;stage:string;objective:string|null;knownContext:string|null;requestedNeed:string|null;status:string;agentName:string;agentStatus:string;executiveSummary:string|null;currentStageSummary:string|null;confirmedFacts:unknown;assumptions:unknown;openQuestions:unknown;risks:unknown;nextActions:unknown;readinessScore:number};
type MemoryRow={id:string;category:string;content:string;sourceType:string;sourceLabel:string|null;confidence:string;createdAt:Date};
const list=(value:unknown)=>Array.isArray(value)?value.map(String):[];

export default async function ProjectDossierPage({params}:{params:Promise<{locale:string;opportunityId:string}>}){const {locale,opportunityId}=await params;const {partner}=await requirePartner(locale);const projects=await prisma.$queryRaw<ProjectRow[]>`SELECT o."id",o."name",o."targetCompany",o."clientContact",o."stage",o."objective",o."knownContext",o."requestedNeed",o."status",a."name" AS "agentName",a."status" AS "agentStatus",m."executiveSummary",m."currentStageSummary",m."confirmedFacts",m."assumptions",m."openQuestions",m."risks",m."nextActions",m."readinessScore" FROM "PartnerOpportunity" o JOIN "ProjectAgent" a ON a."opportunityId"=o."id" JOIN "ProjectMemory" m ON m."opportunityId"=o."id" WHERE o."id"=${opportunityId} AND o."partnerId"=${partner.id} LIMIT 1`;const project=projects[0];if(!project)notFound();const entries=await prisma.$queryRaw<MemoryRow[]>`SELECT "id","category","content","sourceType","sourceLabel","confidence","createdAt" FROM "ProjectMemoryEntry" WHERE "opportunityId"=${opportunityId} AND "isCurrent"=true ORDER BY "createdAt" DESC LIMIT 50`;
const sections=[['Hechos confirmados',list(project.confirmedFacts)],['Supuestos de trabajo',list(project.assumptions)],['Preguntas abiertas',list(project.openQuestions)],['Riesgos',list(project.risks)],['Próximas acciones',list(project.nextActions)]] as const;
return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href={`/${locale}/partner/projects`} className="text-sm text-slate-500">← Proyectos</Link><p className="mt-4 text-xs font-semibold uppercase tracking-[0.16em] text-red-600">Expediente vivo</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">{project.name}</h2><p className="mt-2 text-sm text-slate-500">{project.targetCompany} · {project.stage}</p></div><Button asChild><Link href={`/${locale}/partner/projects/${project.id}/agent`}>Trabajar con el agente</Link></Button></div>
<div className="grid gap-4 md:grid-cols-4"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Preparación</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold">{project.readinessScore}%</p><p className="mt-2 text-xs text-slate-500">No equivale a aprobación comercial.</p></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Project Agent</CardTitle></CardHeader><CardContent><p className="font-medium">{project.agentName}</p><p className="mt-2 text-xs text-slate-500">{project.agentStatus}</p></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Contacto</CardTitle></CardHeader><CardContent><p className="font-medium">{project.clientContact||'Por confirmar'}</p></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Estado</CardTitle></CardHeader><CardContent><p className="font-medium">{project.status}</p></CardContent></Card></div>
<div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-6"><Card><CardHeader><CardTitle>Contexto del proyecto</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="font-semibold">Objetivo</p><p className="mt-1 text-slate-600">{project.objective||'Pendiente de definir.'}</p></div><div><p className="font-semibold">Necesidad planteada</p><p className="mt-1 text-slate-600">{project.requestedNeed||'Pendiente de confirmar.'}</p></div><div><p className="font-semibold">Resumen ejecutivo</p><p className="mt-1 text-slate-600">{project.executiveSummary||'El agente aún no ha consolidado un resumen.'}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Memoria trazable</CardTitle></CardHeader><CardContent className="space-y-3">{entries.length===0?<p className="text-sm text-slate-500">Todavía no hay entradas de memoria.</p>:entries.map(e=><div key={e.id} className="rounded-xl border p-3"><div className="flex flex-wrap gap-2 text-xs font-semibold"><span>{e.category}</span><span className="text-slate-400">·</span><span className="text-red-600">{e.confidence}</span></div><p className="mt-2 text-sm">{e.content}</p><p className="mt-2 text-xs text-slate-500">Fuente: {e.sourceLabel||e.sourceType}</p></div>)}</CardContent></Card></div><div className="space-y-4">{sections.map(([title,items])=><Card key={title}><CardHeader className="pb-2"><CardTitle className="text-sm">{title}</CardTitle></CardHeader><CardContent>{items.length===0?<p className="text-sm text-slate-500">Sin elementos todavía.</p>:<ul className="space-y-2 text-sm">{items.map((x,i)=><li key={i}>• {x}</li>)}</ul>}</CardContent></Card>)}</div></div></div>}
