import Link from 'next/link';
import { notFound } from 'next/navigation';
import { prisma } from '@trends172tech/db';
import { requirePartner } from '@/lib/partners/access';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

type AgentContext={id:string;name:string;targetCompany:string;stage:string;objective:string|null;requestedNeed:string|null;agentName:string;executiveSummary:string|null;readinessScore:number};
export default async function ProjectAgentPage({params}:{params:Promise<{locale:string;opportunityId:string}>}){const {locale,opportunityId}=await params;const {partner}=await requirePartner(locale);const rows=await prisma.$queryRaw<AgentContext[]>`SELECT o."id",o."name",o."targetCompany",o."stage",o."objective",o."requestedNeed",a."name" AS "agentName",m."executiveSummary",m."readinessScore" FROM "PartnerOpportunity" o JOIN "ProjectAgent" a ON a."opportunityId"=o."id" JOIN "ProjectMemory" m ON m."opportunityId"=o."id" WHERE o."id"=${opportunityId} AND o."partnerId"=${partner.id} LIMIT 1`;const p=rows[0];if(!p)notFound();return <div className="space-y-6"><div><Link href={`/${locale}/partner/projects/${p.id}`} className="text-sm text-slate-500">← Expediente</Link><p className="mt-4 text-xs font-semibold uppercase tracking-[0.16em] text-red-600">Project Agent</p><h2 className="mt-1 text-3xl font-semibold">{p.agentName}</h2><p className="mt-2 text-sm text-slate-500">Contexto aislado: {p.name} · {p.targetCompany}</p></div><div className="grid gap-6 xl:grid-cols-[1fr_340px]"><Card><CardHeader><CardTitle>Conversación del proyecto</CardTitle></CardHeader><CardContent><div className="rounded-xl border border-dashed p-6"><p className="font-medium">Workspace preparado para conectar al orquestador.</p><p className="mt-2 text-sm leading-6 text-slate-500">El agente recibirá únicamente el expediente de esta oportunidad, recuperará memoria relevante y podrá invocar especialistas de investigación, levantamiento, estrategia B2B, arquitectura y propuestas. La persistencia se realizará en ProjectMemory y ProjectMemoryEntry.</p><div className="mt-5 flex flex-wrap gap-2"><Button disabled>Enviar mensaje</Button><Button variant="outline" disabled>Adjuntar documento</Button></div></div></CardContent></Card><div className="space-y-4"><Card><CardHeader><CardTitle className="text-sm">Contexto cargado</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div><p className="font-semibold">Etapa</p><p>{p.stage}</p></div><div><p className="font-semibold">Objetivo</p><p>{p.objective||'Pendiente'}</p></div><div><p className="font-semibold">Necesidad</p><p>{p.requestedNeed||'Pendiente'}</p></div></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Readiness</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold">{p.readinessScore}%</p><p className="mt-2 text-xs text-slate-500">El agente debe elevarlo con evidencia, no con suposiciones.</p></CardContent></Card></div></div></div>}
