import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getStudioProjectDetail } from '@/lib/engineering-studio/store';
import { getProjectRoutingProfile } from '@/lib/engineering-studio/routing';
import { approveBlueprintAction, prepareAgentRunAction } from './actions';

type ArchitectureItem = { area?: string; detail?: string };
function asStringArray(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []; }
function asArchitecture(value: unknown): ArchitectureItem[] { return Array.isArray(value) ? value.filter((item): item is ArchitectureItem => Boolean(item && typeof item === 'object')) : []; }
function money(value: { toString(): string } | null) { return value ? `$${Number(value.toString()).toLocaleString('en-US', { maximumFractionDigits: 2 })}` : '—'; }
const profileLabel = { ECONOMY: 'Económico', STANDARD: 'Estándar', ASTRA: 'Astra / Alta complejidad' } as const;

export default async function ProjectBlueprintPage({ params }: { params: Promise<{ locale: string; projectId: string }> }) {
  const { locale, projectId } = await params;
  const project = await getStudioProjectDetail(projectId);
  if (!project) notFound();
  const routingProfile = await getProjectRoutingProfile(projectId);
  const architecture = asArchitecture(project.architectureJson);
  const assumptions = asStringArray(project.assumptionsJson);
  const risks = asStringArray(project.risksJson);
  const agents = asStringArray(project.agentsJson);
  const approved = project.approvalStatus === 'APPROVED';
  return <div className="space-y-6">
    <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-950 sm:p-8"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Project Blueprint · Persistido</p><h3 className="mt-2 text-3xl font-semibold tracking-[-0.03em]">{project.name}</h3><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-500">{project.understanding||project.mvpObjective||project.summary}</p><p className="mt-2 text-xs text-slate-400">{project.clientName||'Proyecto interno'} · {project.mode} · Blueprint v{project.blueprintVersion||1}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">{project.blueprintStatus||'READY'}</span><span className="rounded-full bg-cyan-50 px-3 py-1.5 text-xs font-semibold text-cyan-700">Orquestador: {profileLabel[routingProfile]}</span><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">{project.stage}</span></div></div></section>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><div className="space-y-6">
      <section className="rounded-[26px] border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-950"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Arquitectura preliminar</p><div className="mt-5 grid gap-3 md:grid-cols-2">{architecture.map((item,index)=><div key={`${item.area}-${index}`} className="rounded-2xl border border-slate-200 p-4 dark:border-slate-800"><p className="font-semibold">{item.area||'Área'}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.detail||'Pendiente de análisis'}</p></div>)}</div></section>
      <section className="rounded-[26px] border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-950"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Equipo propuesto</p><div className="mt-4 flex flex-wrap gap-2">{agents.map(agent=><span key={agent} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700 dark:bg-slate-900 dark:text-slate-200">{agent}</span>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">El perfil de orquestación decide el nivel de modelo. Astra no se activa automáticamente en perfiles económicos.</p></section>
      <section className="rounded-[26px] border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-950"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Riesgos y supuestos</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-2xl bg-amber-50 p-4"><p className="text-sm font-semibold">Supuestos</p>{assumptions.map(item=><p key={item} className="mt-2 text-xs">• {item}</p>)}</div><div className="rounded-2xl bg-rose-50 p-4"><p className="text-sm font-semibold">Riesgos</p>{risks.map(item=><p key={item} className="mt-2 text-xs">• {item}</p>)}</div></div></section>
    </div><aside className="space-y-6">
      <section className="rounded-[26px] border border-slate-200 bg-slate-950 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">Forecast preliminar</p><div className="mt-5 space-y-3">{[['Referencia comercial',money(project.recommendedPrice)],['Costo interno orientativo',money(project.estimatedInternalCost)],['OPEX mensual estimado',money(project.estimatedOpexMonthly)],['IA local',project.localAiRequired?'Evaluar':'No requerida']].map(([label,value])=><div key={label} className="flex justify-between gap-3 rounded-xl border border-white/10 bg-white/5 px-4 py-3"><span className="text-xs text-slate-400">{label}</span><span className="text-sm font-semibold">{value}</span></div>)}</div></section>
      <section className={`rounded-[26px] border p-6 ${approved?'border-emerald-200 bg-emerald-50':'border-cyan-200 bg-cyan-50'}`}><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-700">Approval Gate A</p><h4 className="mt-2 text-xl font-semibold">{approved?'Blueprint aprobado':'Pendiente de aprobación'}</h4><p className="mt-2 text-sm leading-6 text-slate-600">{approved?'Baseline v1 congelado. Ya puedes preparar una ejecución supervisada.':'Aprobar congela Baseline v1 y habilita la siguiente fase. No ejecuta modelos por sí solo.'}</p>{!approved&&<form action={approveBlueprintAction} className="mt-5"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="locale" value={locale}/><button type="submit" className="w-full rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Aprobar Blueprint y Baseline v1</button></form>}</section>
      {approved&&<section className="rounded-[26px] border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-950"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Preparar Agent Run</p><h4 className="mt-2 text-lg font-semibold">Nueva tarea supervisada</h4><p className="mt-2 text-xs leading-5 text-slate-500">Prepara rama GitHub, routing, runtime NVIDIA y auditoría. No consume el modelo todavía.</p><form action={prepareAgentRunAction} className="mt-4"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="locale" value={locale}/><textarea required minLength={20} name="task" rows={4} placeholder="Ej.: mejorar el flujo de inscripción, ejecutar pruebas y preparar Preview sin tocar producción." className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-slate-800 dark:bg-slate-900"/><button type="submit" className="mt-3 w-full rounded-full bg-cyan-600 px-5 py-3 text-sm font-semibold text-white">Preparar ejecución</button></form></section>}
      <Link href={`/${locale}/admin/programming/projects`} className="block rounded-full border border-slate-200 px-5 py-3 text-center text-sm font-semibold">Volver a Proyectos</Link>
    </aside></div>
  </div>;
}
